### ISSUE TITLE
解析依頼結果を削除するエンドポイントの追加

### ISSUE THREAD

**Issue by TsutomuNakamura** [a6s-cloud/grouscope-backend#154]
* エンドポイントは`/api/v1/DeleteAnalysisRequests/{id}` とか！？
* 将来的に認証(後回し可: 誰でも好き勝手削除できないようにするための措置)も実装したい

**Comment by nsuzuki7713** [comment]
/api/v1/AnalysisResults/{id} にDELETEメソッドはどうでしょうか？
AnalysisResultsを削除するので、AnalysisResultsの階層でも良さそうな気がしました！！

<img width="626" alt="スクリーンショット 2019-05-12 19 00 23" src="https://user-images.githubusercontent.com/34429882/57580734-3a3fb880-74e8-11e9-99e9-e831dd2922d4.png">

認証なしの削除機能は欲しいですね。テストする際に重複バリデーションで引っかかり、どんな単語入れようか迷います笑
将来的には認証は入れたいです！！Laravelの認証機能で簡単にできるのかな🤔

**Comment by TsutomuNakamura** [comment]
こちら取り掛かりまーす🙋‍♂️。数日くらいはかかるかもしれません。

**Comment by nsuzuki7713** [comment]
ありがとうございます😊
せっかくなので別イシューで良いので、swaggerの更新もお願いできればです🙇‍♂️

**Comment by TsutomuNakamura** [comment]
ういーっす！🙆‍♂️
